languageCode = "ko-KR"
languageName = "í•œêµ­ì–´"
languageDirection = "ltr"
weight = 1

title = "AI íŒŒë„ ì† ë‚˜ì•„ê°€ê¸°"
copyright = "&copy; 2024 Congo contributors"

[params]
  dateFormat = "2006ë…„ 01ì›” 02ì¼"
  mainSections = ["posts"]
  description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."

[params.author]
  name = "ë¬¸ì°¬ì›…(ChanWoong Moon)"
  image = "img/cat-profile.jpeg"
#  image = "img/AB4353BF-16C2-4042-BE85-1700148941DC_4_5005_c.jpeg"
  headline = "ìƒˆë¡œìš´ ê²½í—˜ì„ ì¦ê²¨ìš” :smile:"
  bio = "ğŸš€ Software Developer"
  links = [
#    { x-twitter = "https://twitter.com/" },
    { linkedin = "https://www.linkedin.com/in/chanwoong-moon-0b215b208/" },
    { instagram = "https://www.instagram.com/cold_woong.moon/" },
#    { youtube = "https://youtube.com/" },
  ]